### ISSUE TITLE
libovr or openvr?

### ISSUE THREAD

**Issue by shazow** [rust-openvr/rust-openvr#10]
Hi there, I randomly stumbled on this repo and I noticed it's binding against Valve's OpenVR (actually what I was looking for) while the description says it's binding against LibOVR which is the name for Oculus's SDK.

Am I mistaken, or should the description be updated accordingly?

(The names of openvr vs libovr are totally confusing.)

**Comment by csherratt** [comment]
It use to be based bindings for libovr but I moved to Valve's OpenVR. So the readme file is out of date and I should update it.

**Comment by shazow** [comment]
Ah cool. Happy to send a PR if that'd be easier for you. :) You'll need to get the Github project description, also.

**Comment by csherratt** [comment]
Sure! I haven't tested these bindings in a few months and OpenVR might have had a backward incompatible change in that time. So there be dragons, but I hope it can be helpful to you.

**Comment by shazow** [comment]
Actually I haven't gotten it to fully run/build yet, so that PR will have to wait. Still just getting warmed up with rust/openvr. Feel free to beat me to it. :)

**Comment by Auruss** [comment]
We're using openvr 0.1.19. Readme has been updated :)
