### ISSUE TITLE
Linux build failing

### ISSUE THREAD

**Issue by Auruss** [rust-openvr/rust-openvr#14]
Test status is currently red (failing)

Travis (Linux) seems to have a problem with finding the library for some reason

**Comment by acdimalev** [comment]
This looks like a problem over in rust-openvr-sys.  The lib and bin files for Linux are shared object files, not static archives, so static linking is failing.

I was able to get it to compile successfully with a one-line change.

```diff
diff --git a/lib.rs b/lib.rs
index e1f3fc6..59e5c93 100644
--- a/lib.rs
+++ b/lib.rs
@@ -1,6 +1,6 @@
 #![allow(warnings)]
 
-#[link(name = "openvr_api", kind = "static")]
+#[link(name = "openvr_api")]
 extern {}
 
 /* automatically generated by rust-bindgen */
```

Hope that helps!

**Comment by Auruss** [comment]
thanks! I'm not so sure about this, as far as I know the kind=static will make sure openvr.lib is statically compiled into the openvr-sys binary, therefore when adding openvr-sys as dependency it will also add openvr.lib.

**Comment by Auruss** [comment]
welp, I changed the behavior for linux now to dynamically link against openvr, which does indeed make more sense in linux environments. For windows though static links are more common and will be kept the way it is.
