### ISSUE TITLE
DLL placement

### ISSUE THREAD

**Issue by carlosdp** [rust-openvr/rust-openvr#20]
Where exactly do I need to be placing the DLL?

I've placed it in the project root (where Cargo.toml is), where the .exe is, and everywhere else I can think of and I'm still getting a "test.exe has stopped working" from Windows when calling `openvr::init()` =/

**Comment by Auruss** [comment]
It should be in the working directory of the exe file. But this "... has stopped working" worries me a little bit. If I explicitly remove the dll I get this error message and then a "clean" shutdown

>  ---------------------------
> opengl.exe - System Error
> ---------------------------
> The program can't start because openvr_api.dll is missing from your computer. Try reinstalling the program to fix this problem. 
> ---------------------------
> OK   
> ---------------------------

Can you maybe also check the openvr logs? You can find them in the SteamVR developer settings. There should be log for your exe in that folder (for instance teste.exe.log)

**Comment by carlosdp** [comment]
There doesn't appear to be a SteamVR log for any of the executables I tried

**Comment by carlosdp** [comment]
This includes any of the examples, eg `cargo run --example test`

**Comment by Auruss** [comment]
Now thats weird, I just realized that actually the dll is now (or should be) built into the openvr-sys crate.

Even without an hmd plugged in, the test example starts but prints and error and exits.

**Comment by Auruss** [comment]
Maybe you are using and dll that is too new? It is supposed to be compatible but who knows? The dll that I'm using is part of openvr-sys

**Comment by carlosdp** [comment]
I tried switching it out with both 64 and 32 bit versions from openvr-sys, didn't work. I get the same message if I remove the dll entirely too.

**Comment by Auruss** [comment]
Are you sure you are using the MSVC abi version of rust?

**Comment by carlosdp** [comment]
How would I confirm that? I'm using whatever the rustlang installer gives me `rustc 1.11.0 (9b21dcd6a 2016-08-15)`

**Comment by Auruss** [comment]
https://www.rust-lang.org/en-US/downloads.html there are 2 versions, openvr will only work using MSVC ABI. Unforunately I don't know how to check what you currently have.

**Comment by carlosdp** [comment]
Oh, looks like the default is the GNU abi version, I'll try installing the MSVC one instead and see if that works

**Comment by carlosdp** [comment]
Yep, that did it, thanks for the help!

**Comment by Auruss** [comment]
Yeah well, sorry for the confusion. I need to add it to the readme
