### ISSUE TITLE
Render model indices

### ISSUE THREAD

**Issue by magnonellie** [rust-openvr/rust-openvr#37]
While I'm not exactly sure what's the expected behavior here, I do think there is something odd going on. Attempting to call indices for each tracker model that is found with the following debug messages:
```
pub fn indices(&self) -> &[u16] {
    unsafe {
        let model = &*self.ptr;
        println!("tri count {}", model.unTriangleCount);
        println!("model.rIndexData = {:?}", model.rIndexData);
        eprintln!("model.unVertexCount = {:?}", model.unVertexCount);
        eprintln!("slice = {:?}", slice::from_raw_parts(model.rIndexData, 3 * model.unTriangleCount as usize));
        slice::from_raw_parts(model.rIndexData, 3 * model.unTriangleCount as usize)
    }
}
```
yields this output:
```
tri count 0
model.rIndexData = 0x16ba00007f2a
model.unVertexCount = 17454
slice = []
tri count 1
model.rIndexData = 0x9ae00007f2a
model.unVertexCount = 2638
slice = [
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
```
I find it hard to believe that the models don't have any indices first of all and that segfault isn't what I would call expected behavior. This is all on Fedora 28 by the way. If somebody could assist me in debugging this or maybe just tell me that it's a known bug / quirk, that would be very appreciated. :smile:

**Comment by Ralith** [comment]
That's certainly strange. What's the value of `rIndexData`? What device are you querying the model of?

**Comment by magnonellie** [comment]
I was attempting to query the model of the HMD (generic_hmd), but this also happens for all other models (lh_basestation_vive, vr_controller_vive_1_5). I should also point out that I've tested this code in Windows now where it works without problem. I don't unfortunately know how to get anything other than the pointer value of `rIndexData` but maybe you could point me in the right direction?

**Comment by Ralith** [comment]
> I was attempting to query the model of the HMD (generic_hmd), but this also happens for all other models (lh_basestation_vive, vr_controller_vive_1_5).

Vive HMD, too? No weird VR hardware/software installed? Interesting; I too have validated that configuration on windows. I assume SteamVR itself has no trouble displaying the controller models, so we must be doing something wrong. At a guess, this is another one of SteamVR's ABI disasters, where the header lies about the actual layout of the types.

> I don't unfortunately know how to get anything other than the pointer value of rIndexData but maybe you could point me in the right direction?

I mean, what specifically is the pointer? Just `p model.rIndexData`.

`p/x model` in its entirety would be interesting too, as it might provide some clues as to what the ABI mismatch is.

**Comment by magnonellie** [comment]
Yep, just a normal non-pro vive without any weird hardware or software. It's basically just what I got out of the box. SteamVR, SteamVR home and the OpenGL OpenVR sample all work and shows the controllers. Again, I'm not good with GDB at all, but I hope this helps:
```
(gdb) p model.rIndexData 
$9 = (u16 *) 0x9ae00007fff
(gdb) p/x model
$10 = 0x7fffde014040
(gdb) p *model.rIndexData 
Cannot access memory at address 0x9ae00007fff
(gdb) p/x *model
$11 = openvr_sys::RenderModel_t {rVertexData: 0x7fffde19e100, unVertexCount: 0xa4e, rIndexData: 0x9ae00007fff, unTriangleCount: 0x2, diffuseTextureId: 0x0}
```

**Comment by Ralith** [comment]
I'm guessing the problem is the one alluded to by [a comment in openvr.h](https://github.com/ValveSoftware/openvr/blob/master/headers/openvr.h#L3574). Try putting `#[cfg_attr(unix, repr(packed))]` above the definition of `RenderModel_t` in bindings.rs.

**Comment by magnonellie** [comment]
Yup, that did the trick! Had to do it for `RenderModel_TextureMap_t` also and I suspect it's not the last one that's gonna need it either.

![screenshot from 2018-08-23 11-56-31](https://user-images.githubusercontent.com/4590037/44518921-df510180-a6cb-11e8-903c-36492d4db93b.png)

You're a hero btw :smile:

**Comment by Ralith** [comment]
Glad it worked! I just published an update to openvr-sys covering all the cases of that comment that I found in the header, so you should be able to use crates.io again now. Let me know if there's any other issues!
